name: Merge any release branch to uat
on:
  push:
    branches:
      #- 'release/*'
      - release
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge to main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{secrets.GITHUB_TOKEN}}