name: Merge branch with labeled
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Merge by labeled
        uses: devmasx/merge-branch@1.4.0
        with:
          label_name: 'development'
          target_branch: 'development'
          github_token: ${{ github.token }}