# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2

      - run: pnpm i

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15, 16]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      
      - name: Use pnpm package manager
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2

      - name: Install dependencies
      - run: pnpm i

      - name: Run Husky prepare scritps
      - run: pnpm prepare

      - name: Publish to NPM
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2

      - run: pnpm i
      - run: pnpm prepare
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
