# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15, 16]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Nodejs v${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Configure PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2
      - name: PNPM install
        run: pnpm i
      - name: PNPM build
        run: pnpm build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15, 16]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2

      - name: Configure Nodejs v${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: PNPM install
        run: pnpm i

      - name: Publish to NPM
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2

      - run: pnpm i
      - run: pnpm prepare
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
