name: Create Release

on:
  push:
    branches:
      - staging
    branches-ignore:

    tags:
      - v*.*.*
      - 'v*'
    tags-ignore:
      - *-alpha
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      uses: elgohr/Github-Release-Action@v3.1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: MyReleaseMessage