name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge development -> staging
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: development
          target_branch: staging
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Merge staging -> release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: release
          github_token: ${{secrets.GITHUB_TOKEN}}